name: Go Hello Web Service
on:
  push:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.18'

      - name: Build the web service
        run: |
          go build -o hello ./cmd/hello

      - name: Run the web service
        run: |
          ./hello
